apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: core-service-binding
subjects:
  - kind: ServiceAccount
    name: core-service-sa
roleRef:
  kind: Role
  name: core-service-role
  apiGroup: rbac.authorization.k8s.io
